/* ---------- M2 App ---------- */
function loadApp(){
 get("/api/app").then(function(d){if(d.error){$("#apMode").innerHTML='<div class="err">'+esc(d.error)+'</div>';return}
  $("#apTiles").innerHTML=tile(d.users.ever,"Members who have used the app")+tile(d.users.week,"Used it this week")+tile(d.users.week_core,"Served by the Core this week")+tile(d.requests.filter(function(r){return !r.done_at}).length,"Requests to handle");
  var M=[["off","Nobody yet","The old Google service answers everything, as before."],["staff","Staff only","Staff are served by the Core. Use this to test on your own phones."],["all","Everyone","Every member is served by the Core."]];
  $("#apMode").innerHTML=M.map(function(m){return '<label style="display:flex;gap:10px;align-items:flex-start;margin:10px 0;cursor:pointer"><input type="radio" name="apm" value="'+m[0]+'"'+(d.mode===m[0]?" checked":"")+' style="margin-top:4px"> <span><b>'+m[1]+'</b><br><span class="muted" style="font-size:13px">'+m[2]+'</span></span></label>'}).join("")+'<div id="apModeMsg"></div>';
  var R=d.ready,steps=[];
  if(!R.secret)steps.push('<li>In the Google script <b>M2 APP Service</b>, open Project Settings, Script properties, and copy the value of <b>SESSION_SECRET</b>. In Cloudflare, Workers, <b>m2-core</b>, Settings, Variables and secrets, add a <b>Secret</b> called <b>APP_SESSION_SECRET</b> with that same value. Then members stay signed in whichever side answers.</li>');
  if(!R.staff_key||!R.member_key)steps.push('<li>The GymMaster keys (GM_API_KEY and GM_STAFF_KEY) are missing on m2-core.</li>');
  var sc=d.secret_check||"";if(R.secret&&!steps.length){steps=null;$("#apReady").innerHTML=/^match/.test(sc)?'<div class="ok" style="margin-top:10px">Ready. The shared secret matches the Google service (checked on a real sign-in).</div>':/^nomatch/.test(sc)?'<div class="err" style="margin-top:10px">APP_SESSION_SECRET doesn\'t match SESSION_SECRET in the Google script. Copy it again before switching on, or people get signed out.</div>':'<div class="warnbox" style="margin-top:10px">Keys are in. The secret gets checked the next time someone signed in opens the app (open it on your phone). Wait for the green tick before switching on.</div>'}else
$("#apReady").innerHTML=steps.length?'<div class="warnbox" style="margin-top:10px"><b>One step before switching on</b><ol style="margin:8px 0 0 18px">'+steps.join("")+'</ol></div>':'<div class="ok" style="margin-top:10px">Ready. Keys and the shared session secret are in.</div>';
  var N={front:"Front door",male:"Men's recovery",female:"Women's recovery",door4:"Fourth door"};
  $("#apDoors").innerHTML=Object.keys(N).map(function(k){return '<label class="fld">'+N[k]+'<input data-apd="'+k+'" inputmode="numeric" value="'+esc(d.doors[k]||"")+'" placeholder="Old service opens it"></label>'}).join("")+'<button class="btn dark" id="apDoorSave">Save doors</button><div id="apDoorMsg"></div>';
  $("#apCoach").innerHTML=[["google","Google service","As before: ticks go into GymMaster."],["core","M2 Core","Ticks are saved in the Core."]].map(function(m){return '<label style="display:flex;gap:10px;align-items:flex-start;margin:8px 0;cursor:pointer"><input type="radio" name="apc" value="'+m[0]+'"'+(d.coach===m[0]?" checked":"")+' style="margin-top:4px"> <span><b>'+m[1]+'</b><br><span class="muted" style="font-size:13px">'+m[2]+'</span></span></label>'}).join("")+'<div id="apCoachMsg"></div>'+(d.coach_log&&d.coach_log.length?'<div style="overflow-x:auto;margin-top:8px">'+table([["When",function(r){return fmtWhen(r.at)}],["Class",function(r){return esc(r.name+" "+String(r.start||"").slice(0,5)+", "+r.day)},0,1],["Member",function(r){return '<a href="#" data-member="'+r.member_id+'">'+esc(nm(r))+'</a>'},0,1],["What","what"],["By","by_name"]],d.coach_log)+'</div>':"");
  $("#apReq").innerHTML=d.requests.length?table([["When",function(r){return fmtWhen(r.at)}],["Member",function(r){return '<a href="#" data-member="'+r.member_id+'">'+esc(nm(r))+'</a>'},0,1],["Request",function(r){return ({delete:"Delete my account",upgrade:"Upgrade",feedback:"Feedback",hold:"Hold",cancel:"Cancel"})[r.kind]||r.kind}],["Message","text"],["",function(r){return r.done_at?'<span class="muted">Done by '+esc(r.done_by||"")+'</span>':'<a href="#" data-apdone="'+r.id+'">Mark done</a>'},0,1]],d.requests):'<div class="muted">Nothing yet. Requests sent through the Core show here.</div>';
  $("#apDoorLog").innerHTML=d.door_log.length?table([["When",function(r){return fmtWhen(r.at)}],["Member",function(r){return '<a href="#" data-member="'+r.member_id+'">'+esc(nm(r))+'</a>'},0,1],["Door","door"],["Opened",function(r){return r.opened?"Yes":"No"}],["Note","note"],["Metres away","metres",1]],d.door_log):'<div class="muted">No doors opened through the Core yet.</div>';
 });
}
function fmtWhen(s){var d=new Date(String(s).replace(" ","T")+"Z");return d.toLocaleString("en-NZ",{weekday:"short",day:"numeric",month:"short",hour:"numeric",minute:"2-digit"})}
$("#apMode").addEventListener("change",function(e){if(e.target.name!=="apm")return;post("/api/app",{mode:e.target.value}).then(function(r){if(!r.ok){$("#apModeMsg").innerHTML='<div class="err">'+esc(r.error)+'</div>';loadApp();return}$("#apModeMsg").innerHTML='<div class="ok">Saved.</div>'})});
$("#apCoach").addEventListener("change",function(e){if(e.target.name!=="apc")return;post("/api/app",{coach:e.target.value}).then(function(r){$("#apCoachMsg").innerHTML=r.ok?'<div class="ok">Saved.</div>':'<div class="err">'+esc(r.error)+'</div>'})});
$("#apDoors").addEventListener("click",function(e){if(!e.target.closest("#apDoorSave"))return;var o={};document.querySelectorAll("[data-apd]").forEach(function(i){o[i.dataset.apd]=i.value});post("/api/app",{doors:o}).then(function(r){$("#apDoorMsg").innerHTML=r.ok?'<div class="ok">Saved.</div>':'<div class="err">'+esc(r.error)+'</div>'})});
$("#apReq").addEventListener("click",function(e){var a=e.target.closest("[data-apdone]");if(!a)return;e.preventDefault();post("/api/app/request/"+a.dataset.apdone,{}).then(loadApp)});
$("#apPrevGo").addEventListener("click",function(){var id=$("#apPrevId").value.replace(/\D/g,"");if(!id)return;get("/api/app/preview/"+id).then(function(d){if(d.error){$("#apPrev").innerHTML='<div class="err">'+esc(d.error)+'</div>';return}
 var m=d.member;$("#apPrev").innerHTML='<div class="tiles">'+tile(m.first+" "+m.last,"Name")+tile(d.tier||"none","App tier")+tile(m.totalvisits,"Visits")+tile(d.days.length,"Days in the last 400")+'</div><p class="muted" style="margin-top:8px">Memberships: '+esc(d.memberships.map(function(x){return x.name}).join(", ")||"none")+(d.pass?". Pass: "+esc(d.pass.name)+(d.pass.left!=null?", "+d.pass.left+" days left":""):"")+(m.staff?". Staff":"")+(m.coach?", coach":"")+'</p>'})});

function navLabels(){document.querySelectorAll("nav .navlab").forEach(function(l){var n=l.nextElementSibling,any=false;while(n&&!n.classList.contains("navlab")){if(!n.hidden)any=true;n=n.nextElementSibling}l.hidden=!any})}

function loadFpCheck(fresh){var m=$("#fpMonth").value;$("#fpCheck").innerHTML='<div class="muted">'+(fresh?"Asking GymMaster...":"Loading...")+'</div>';
 (fresh?post("/api/passport/check?month="+m,{}):get("/api/passport/check?month="+m)).then(function(d){
  if(d.error){$("#fpCheck").innerHTML='<div class="muted">'+esc(d.error)+'</div>';return}
  if(d.core==null){$("#fpCheck").innerHTML='<div class="muted">Not checked yet for this month. Tap Check this month again.</div>';return}
  var pct=d.members?Math.round(d.same/d.members*1000)/10:0,gap=d.core-d.gm;
  var h='<div class="tiles">'+tile(d.core.toLocaleString("en-NZ"),"Core count")+tile(d.gm.toLocaleString("en-NZ"),"GymMaster count")+(d.fp!=null?tile(d.fp.toLocaleString("en-NZ"),"Passport paid for"):"")+tile(pct+"%","Members that match")+'</div>';
  var thisMonth=m===new Date().toLocaleDateString("en-CA",{timeZone:"Pacific/Auckland"}).slice(0,7);
  if(thisMonth)h+='<div class="muted" style="margin-top:10px">This month is still running and GymMaster\'s visit report runs a few hours behind, so today\'s visits won\'t match yet. Pick last month for the real check.</div>';
  else h+=Math.abs(gap)<=Math.max(5,d.gm*0.005)&&pct>=98?'<div class="ok" style="margin-top:10px">Close enough to switch over: the counts are within half a percent.</div>':'<div class="warnbox" style="margin-top:10px">'+(gap<0?"The Core is missing "+(-gap)+" visits that GymMaster has.":"The Core has "+gap+" more visits than GymMaster.")+' Not ready to take over yet.</div>';
  if(d.diffs&&d.diffs.length)h+='<details style="margin-top:10px"><summary class="muted" style="cursor:pointer">See the '+d.diff_count+' member'+(d.diff_count===1?"":"s")+' that differ</summary><div style="overflow-x:auto;max-height:320px;overflow-y:auto;margin-top:6px">'+table([["Member",function(r){return '<a href="#" data-member="'+r.member_id+'">'+esc(r.name)+'</a>'},0,1],["Core","core",1],["GymMaster","gm",1]],d.diffs)+'</div></details>';
  $("#fpCheck").innerHTML=h});
}
$("#fpCheckRun").addEventListener("click",function(){loadFpCheck(true)});

