/* ---------- Insights ---------- */
function ibars(rows,keyI,fmt){var max=Math.max.apply(null,rows.map(function(r){return r.n}).concat([1]));return rows.map(function(r,i){return '<div class="hb2'+(i===keyI?" key":"")+'"><span>'+esc(r.label)+'</span><div class="bar"><i style="width:'+Math.max(r.n?2:0,Math.round(r.n/max*100))+'%"></i></div><span class="v">'+(fmt?fmt(r):r.n.toLocaleString("en-NZ"))+'</span></div>'}).join("")}
function maxI(rows){var b=0;rows.forEach(function(r,i){if(r.n>rows[b].n)b=i});return b}
function icard(q,sub,body,alert,cls){return '<section class="card"><div><div class="eyebrow">'+esc(sub)+'</div><h2 style="margin-top:4px">'+esc(q)+'</h2></div>'+body+(alert?'<div class="alert '+(cls||"lime")+'">'+alert+'</div>':"")+'</section>'}
var INS=null;
function loadIns(){get("/api/insights").then(function(d){
 if(d.error){$("#inC").innerHTML='<div class="err">'+esc(d.error)+'</div>';return}INS=d;
 var pct=function(a,b){return b?Math.round(a/b*100)+"%":"-"};
 $("#inK").innerHTML='<div class="kp"><label>Members</label><b>'+d.kpis.members.toLocaleString("en-NZ")+'</b><small>No staff, trials or passes</small></div><div class="kp"><label>Paying</label><b>'+d.kpis.paying.toLocaleString("en-NZ")+'</b><small>Direct debit</small></div><div class="kp"><label>Fitness Passport</label><b>'+d.kpis.passport.toLocaleString("en-NZ")+'</b><small>Paid per visit</small></div><div class="kp"><label>Source recorded</label><b>'+d.kpis.source_pct+'%</b><small>Of current members</small></div>';
 var c=[],mn=d.month_name;
 var p0=d.paying.buckets[0].n;
 c.push(icard("Who's paying and not coming?","Paying members by visits in "+mn,ibars(d.paying.buckets,0),'<b>'+p0+' paying members didn\'t come in once in '+esc(mn)+'</b>They\'re the most likely to cancel. They\'re on the red list in Money on the table. <a href="#" data-askq2="Perform members who haven\'t been in 30 days">See who</a>',"red"));
 c.push(icard("Where's the Passport money hiding?","Passport members by visits in "+mn,ibars(d.passport.buckets,0),'<b>'+d.passport.zero.toLocaleString("en-NZ")+' Passport members ('+pct(d.passport.zero,d.passport.total)+') didn\'t visit in '+esc(mn)+'</b>'+(d.passport.extra!=null?'One visit each would have paid about '+money(d.passport.extra)+'. ':'')+'Passport nudges go to the ones who drop below their usual. <a href="#" data-go="passport">Open Passport</a>'));
 // heatmap
 var days=[1,2,3,4,5,6,0],dn={1:"Mon",2:"Tue",3:"Wed",4:"Thu",5:"Fri",6:"Sat",0:"Sun"},hrs=[];for(var h=5;h<=22;h++)hrs.push(h);
 var g={},mx=1;d.heat.forEach(function(x){g[x.dow+"_"+x.hr]=x.n;if(x.n>mx)mx=x.n});
 var all=d.heat.map(function(x){return x.n}).sort(function(a,b){return b-a}),top=all[Math.floor(all.length*.08)]||mx;
 var hm2='<div class="heat"><span></span>'+hrs.map(function(h){return '<span style="justify-content:center">'+(h%3===0?(h>12?h-12:h)+(h>=12?"p":"a"):"")+'</span>'}).join("");
 var best=null;days.forEach(function(dw){hm2+='<span>'+dn[dw]+'</span>'+hrs.map(function(h){var n=g[dw+"_"+h]||0,a=n/mx;if(!best||n>best.n)best={n:n,d:dn[dw],h:h};var col=n>=top?"#DFFF00":"rgba(10,10,10,"+(0.06+a*0.8).toFixed(2)+")";return '<i style="background:'+col+'" title="'+dn[dw]+" "+h+':00, '+n+' entries"></i>'}).join("")});hm2+='</div>';
 c.push(icard("When is the club actually busy?","Entries by day and hour, last 8 weeks",hm2,best?'<b>Busiest: '+best.d+' '+(best.h>12?best.h-12:best.h)+(best.h>=12?"pm":"am")+'</b>Peaks in lime. Put classes, PT sessions and staff where the people are, and promote the quiet hours to Passport members.':""));
 if(d.billing){var b=d.billing,mxb=Math.max.apply(null,b.days.map(function(x){return x.collected+x.failed}).concat([1]));
  var svg='<svg viewBox="0 0 600 170" style="width:100%;height:auto;display:block" role="img" aria-label="Collected and failed by day">'+b.days.map(function(x,i){var X=i*20+2,hc=x.collected/mxb*140,hf=x.failed/mxb*140;return '<rect x="'+X+'" y="'+(150-hc)+'" width="15" height="'+hc+'" rx="3" fill="#0A0A0A"><title>'+esc(day(x.d))+': '+money(x.collected)+' collected, '+money(x.failed)+' failed</title></rect>'+(hf?'<rect x="'+X+'" y="'+(150-hc-hf-2)+'" width="15" height="'+hf+'" rx="3" fill="#C0392B"/>':"")}).join("")+'<text x="2" y="166" font-size="11" fill="#5B5B55">'+esc(day(b.days[0].d))+'</text><text x="598" y="166" font-size="11" fill="#5B5B55" text-anchor="end">'+esc(day(b.days[29].d))+'</text></svg>';
  c.push(icard("Is billing healthy?","Direct debits collected (black) and failed (red), last 30 days",svg,'<b>'+money(b.collected)+' collected. '+b.nf+' of '+(b.n+b.nf).toLocaleString("en-NZ")+' failed ('+b.rate+'%), '+money(b.failed)+'</b>Failed payments go to reception as jobs on Today. <a href="#" data-go="billing">Open Billing</a>',b.rate>5?"amber":"lime"))}
 if(d.cost){var k=d.cost;c.push(icard("What's billing costing you?","Each month",'<div class="tiles"><div class="tile"><div class="n">'+money(k.gm_now)+'</div><div class="l">GymMaster plan</div></div><div class="tile"><div class="n">'+money(k.fees_month)+'</div><div class="l">Ezidebit fees, '+k.debits_month.toLocaleString("en-NZ")+' debits at '+money(k.debit_fee)+(k.fee_confirmed?"":" (not confirmed)")+'</div></div><div class="tile"><div class="n">'+money(k.fortnightly.fees_month)+'</div><div class="l">Fees if weekly payers went fortnightly</div></div></div>','<b>Ask Ezidebit who pays the per-debit fee</b>At '+money(k.debit_fee)+' a debit, M2 paying it would cost about '+money(k.fees_month)+' a month. A doors-only GymMaster plan is the target.',"amber"))}
 var lI=maxI(d.left);
 c.push(icard("How long do members stay?","Current members by time with M2",ibars(d.tenure,-1),d.left.some(function(x){return x.n})?'<b>Most people who left in the last 6 months went at '+esc(d.left[lI].label.toLowerCase())+'</b>That\'s the danger zone. A check-in call or a free PT around then keeps people.':"",'amber'));
 c.push(icard("Who are your members?","Age, of "+d.ages.known.toLocaleString("en-NZ")+" with a birth date",ibars(d.ages.buckets,maxI(d.ages.buckets))+'<div style="margin-top:8px">'+ibars(d.gender,-1)+'</div>','<b>'+esc(d.ages.buckets[maxI(d.ages.buckets)].label)+' is the biggest group ('+pct(d.ages.buckets[maxI(d.ages.buckets)].n,d.ages.known)+')</b>Aim ads and photos at them.'));
 var nr=(d.sources.find(function(x){return x.label==="Not recorded"})||{n:0}).n,st=d.sources.reduce(function(a,x){return a+x.n},0);
 c.push(icard("Where do members come from?","Lead source, current members",ibars(d.sources,-1),'<b>'+pct(nr,st)+' have no source recorded</b>"How did they hear about M2?" is now required at sign-up, so this fills in from here.',nr/st>.5?"red":"lime"));
 c.push(icard("Are new members sticking?","Current members by the month they joined",ibars(d.cohorts.map(function(x){return {label:new Date(x.label+"-01T12:00:00").toLocaleDateString("en-NZ",{month:"short",year:"2-digit"}),n:x.n}}),maxI(d.cohorts)),d.cohorts.length?'<b>'+esc(new Date(d.cohorts[maxI(d.cohorts)].label+"-01T12:00:00").toLocaleDateString("en-NZ",{month:"long",year:"numeric"}))+' is the strongest month still here</b>Look at what ran that month and do it again.':""));
 c.push(icard("What's the front desk dealing with?","Entries the gate turned away, last 30 days",d.denied.length?ibars(d.denied,0):'<div class="muted">Turned-away entries are now being copied from GymMaster. This fills in over the next few days.</div>',d.denied.length?'<b>Top reason: '+esc(d.denied[0].label)+'</b>Fix the cause and reception gets fewer people at the desk.':""));
 if(d.pos){c.push(icard("What's selling at reception?","Point of sale by type, last 30 days",ibars(d.pos.map(function(x){return {label:x.label,n:x.v,c:x.n}}),0,function(r){return kfmt(r.n)}),d.trials_vs_joins?'<b>'+d.trials_vs_joins.trials+' trials and passes vs '+d.trials_vs_joins.joins+' joins in 30 days</b>Every trial should leave with a call booked. Trials ending show on Today.':"","amber"))}
 $("#inC").innerHTML=c.join("");
 if(d.reports){$("#inLib").hidden=false;var sc=d.schedules||{};$("#inLibN").textContent=d.email_on?"Email a report link to yourself":"Scheduling starts once email sending is connected";
  $("#inLibL").innerHTML=d.reports.map(function(r){var cur=(sc[r.kind]||{}).every||"";return '<div class="prow"><div class="g"><div class="t">'+esc(r.title)+'</div></div><button class="btn line sm" data-openrep="'+r.kind+'">Open</button>'+(d.owner?'<select data-sched="'+r.kind+'" data-title="'+esc(r.title)+'" style="height:34px;border:1px solid var(--line);border-radius:999px;padding:0 10px"><option value="">Not emailed</option><option value="weekly"'+(cur==="weekly"?" selected":"")+'>Weekly, Mondays</option><option value="monthly"'+(cur==="monthly"?" selected":"")+'>Monthly, the 1st</option></select>':"")+'</div>'}).join("")}
})}
document.addEventListener("click",function(e){
 var r=e.target.closest("[data-openrep]");if(r){REP.kind=r.dataset.openrep;show("reports");return}
 var a=e.target.closest("[data-askq2]");if(a){e.preventDefault();openAsk(a.dataset.askq2)}
});
document.addEventListener("change",function(e){var s=e.target.closest("[data-sched]");if(!s)return;post("/api/insights/schedule",{kind:s.dataset.sched,title:s.dataset.title,every:s.value}).then(function(x){if(x.error)alert(x.error)})});

