/* ---------- Why M2 Core ---------- */
var ROI=null;
function loadWhy(){get("/api/why").then(function(d){
 var el=document.querySelector('section[data-view="why"]');
 if(d.error){el.innerHTML='<div class="err">'+esc(d.error)+'</div>';return}
 ROI={d:d,paying:d.paying,fp:d.passport,fpv:0.5,churn:0.25,upg:4,hours:10,dev:1500};
 var ck='<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" style="flex:none;margin-top:3px"><path d="M5 12l5 5 9-11"/></svg>';
 var li=function(a){return a.map(function(x){return '<li>'+esc(x)+'</li>'}).join("")};
 var built=[["Today","Live door, calls, plays and the day's jobs"],["Members","Profiles, notes, photos, key tags, the $250 block"],["Sign up","Contract, signature, Passport ID, Bring a Mate"],["Classes","Own timetable, bookings, waitlists and caps"],["Point of sale","Sales at reception"],["PT leads","Tim assigns, trainers get them on their phones"],["Billing engine","Every schedule worked out nightly, in preview"],["Money owed","Full balances, the $250 block and the Marshall Freeman rule"],["Fitness Passport","Visit checks, nudges and the pay tiers"],["M2 App","Bookings, doors by phone, account deletion"],["Email automations","Ready to take over from GymMaster"],["Security","Own logins, two-step sign-in, activity log, nightly backups"]];
 el.innerHTML='<section class="hero"><div style="position:relative;z-index:1"><div class="eb">The case for M2 Core</div><h1>Your members.<br>Your data.<br><em>Your rules.</em></h1></div>'+
 '<p style="margin:0;color:#BDBDB5;max-width:64ch;position:relative;z-index:1">GymMaster costs '+money(d.gm_cost)+' a month. That\'s the small number. The big one is what you can\'t do while your members live in someone else\'s system.</p>'+
 '<div class="hstats" style="position:relative;z-index:1"><div class="hs"><b>'+d.members.toLocaleString("en-NZ")+'</b><span>Members</span><small>No staff, trials or passes</small></div><div class="hs"><b>'+kfmt(d.revenue12)+'</b><span>Revenue, '+d.revenue_months+' months</span><small>Xero'+(d.revenue_from?", "+esc(d.revenue_from)+" to "+esc(d.revenue_to):"")+'</small></div><div class="hs"><b>'+kfmt(d.gm_cost*12)+'</b><span>GymMaster a year</span><small>'+money(d.gm_cost)+' a month</small></div><div class="hs"><b class="l" id="whyUp">-</b><span>Upside a year</span><small>See the maths below</small></div></div></section>'+
 '<div class="vs2"><section class="card"><h3>Rented: GymMaster</h3><ul>'+li(["Reports are monthly exports into spreadsheets.","The app's QR code can't open their doors.","Website, app, PT leads and dashboards each bolt on with a workaround.","Their roadmap, their timeline.","Enterprise pricing because published plans stop at 1,300 members."])+'</ul></section><section class="card dark"><h3 style="color:var(--lime)">Owned: M2 Core</h3><ul style="color:#E9E9E4">'+li(["Every door tap updates a member's health score.","Doors open from the M2 App.","Website, app, staff screens and PT leads share one member record.","M2's rules built in: the $250 block, the Marshall Freeman rule, Passport left out of promos.","Ask a question in plain English and get the list back."])+'</ul></section></div>'+
 '<div class="g2 even"><section class="card dark"><div class="eyebrow">What Ezidebit confirmed, 6 Oct 2026 (Rendy)</div><div>'+
 [["The account is in M2 Training Club's name","Ezidebit holds payers' card and bank details, so members don't re-sign."],["Payment schedules are held by GymMaster","When the GymMaster link stops, charging stops. M2 Core must send the nightly debit instructions from the same night GymMaster's stop."],["Direct connection is allowed, with certification","Sandbox build, then a checklist, then a walkthrough, then a certificate. Renewed every year."]].map(function(x){return '<div class="prow"><div class="g"><div class="t" style="color:#fff;white-space:normal">'+esc(x[0])+'</div><div class="s" style="white-space:normal">'+esc(x[1])+'</div></div></div>'}).join("")+
 '</div><div class="alert amber" style="color:var(--ink)"><b>Still waiting on Ezidebit</b>Whether the authorities sit under M2\'s merchant account. Whether M2\'s own API key can see existing customers. Read-only access for testing. The per-debit fee and who pays it'+(d.debits_month?" (at "+money(d.debit_fee)+" × "+d.debits_month.toLocaleString("en-NZ")+" debits, about "+money(d.debit_fee*d.debits_month)+" a month)":"")+'.</div></section>'+
 '<section class="card"><div class="eyebrow">Keep GymMaster for the doors only</div><h2>GymMaster plans</h2><table class="tbl"><thead><tr><th>Plan</th><th>Members</th><th class="r">A month</th></tr></thead><tbody><tr><td>Advanced</td><td>Up to 400</td><td class="r">$189</td></tr><tr><td>Professional</td><td>Up to 1,300</td><td class="r">$299</td></tr><tr><td><b>Enterprise (now)</b></td><td>Unlimited</td><td class="r">'+money(d.gm_cost)+'</td></tr><tr><td>+ 24/7 door access</td><td>Any plan</td><td class="r">+$50</td></tr></tbody></table><p class="muted" style="margin:0">The target is a doors-only deal near Professional pricing'+(d.gm_doors?", "+money(d.gm_doors)+" a month as entered in Billing":", around $350 a month")+'. GymMaster needs 30 days notice.</p></section></div>'+
 '<div class="g2 even" id="calc"><section class="card"><div class="chead"><h2>Run your own numbers</h2><p>Drag anything you disagree with</p></div><div id="whyS"></div></section><section class="card dark"><h2 style="color:#fff">Year one, once it\'s all running</h2><div class="ledg" id="whyL"></div><p style="margin:0;color:#9A9A92;font-size:12px"><span class="src x">Real</span> numbers come from M2 Core and Xero. <span class="src a">Assumption</span> marks a dial you control. Revenue figures include GST.</p></section></div>'+
 '<section class="card"><div class="chead"><h2>Already built</h2><p>Live in M2 Core today</p></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px">'+built.map(function(x){return '<div style="background:var(--tile);border-radius:14px;padding:12px;display:flex;gap:8px;color:var(--olive)">'+ck+'<div style="color:var(--ink)"><b>'+esc(x[0])+'</b><div class="muted">'+esc(x[1])+'</div></div></div>'}).join("")+'</div></section>'+
 '<div><div class="eyebrow" style="margin-bottom:10px">Roadmap, with a go or no-go at each step</div><div class="phz">'+
 [["Now to October","Run the club from M2 Core",["Staff use M2 Core alongside GymMaster","The M2 App goes live","Milos reviews the code and security"],"Staff prefer it and its numbers match GymMaster every day.",true],["November","Billing in shadow mode",["Export every member's schedule from GymMaster (amount, frequency, next date, end date, Flexi, paid in full, Ezidebit customer ID)","Each night M2 Core works out what it would debit and compares it with GymMaster's real batch. It sends nothing.","Ezidebit certification: sandbox, checklist, walkthrough, certificate"],"Matches GymMaster to the cent for several cycles in a row.",false],["December","Cut over, one planned night",["GymMaster billing stops and M2 Core starts on the same night","GymMaster drops to a doors-only plan","Never both systems sending debits: members would be charged twice"],"The first live week runs clean, with no double debits and no missed ones.",false]].map(function(p){return '<section class="card'+(p[4]?" now":"")+'"><div class="eyebrow">'+esc(p[0])+'</div><h2>'+esc(p[1])+'</h2><ul style="margin:0;padding-left:18px;color:var(--muted);font-size:14px;display:flex;flex-direction:column;gap:5px">'+li(p[2])+'</ul><div class="gate"><b>Go / no-go</b>'+esc(p[3])+'</div></section>'}).join("")+'</div></div>'+
 '<section class="card"><h2>What could go wrong, and the answer</h2>'+[["Members charged twice or not at all","Shadow mode first, one planned cut-over night, and GymMaster's billing is switched off the same night M2 Core's goes on. Ezidebit keeps doing the actual debiting."],["Doors stop working","Doors stay with GymMaster on a doors-only plan. The M2 App opens them as well, and key tags keep working."],["It depends on one person","Milos reviews and can take over. The code, setup and backups are documented, and backups are tested monthly."],["Privacy and hackers","Own login per staff member with two-step sign-in, sessions that lock, an activity log with alerts, nightly backups, no card or bank numbers ever held by M2."],["Ezidebit's fee","Waiting on who pays the per-debit fee. If it's M2, moving weekly payers to fortnightly halves it."],["Staff have to relearn","The screens are simpler than GymMaster's and the team is already using them."]].map(function(x){return '<div class="prow" style="align-items:flex-start"><div class="g" style="flex:0 0 34%"><div class="t" style="white-space:normal">'+esc(x[0])+'</div></div><div class="muted" style="flex:1;font-size:14px">'+esc(x[1])+'</div></div>'}).join("")+'</section>'+
 '<section class="hero"><div style="position:relative;z-index:1"><div class="eb">Recommendation</div><h2 style="color:#fff;font:900 clamp(22px,3vw,32px)/1.1 Archivo,Arial,sans-serif;text-transform:uppercase;margin-top:8px">Run the club from M2 Core now. Shadow billing in November. Cut over in December only if it matches to the cent.</h2><p style="color:#BDBDB5;margin:10px 0 0;max-width:64ch">Nothing about members\' money changes until the numbers prove it. The rest pays for itself through retention, Passport visits and upgrades.</p></div><div style="position:relative;z-index:1"><button class="btn" data-go="plays">See the money on the table</button></div></section>';
 var S=[["paying","Paying members","x",300,2600,10,function(v){return v.toLocaleString("en-NZ")},"From M2 Core today. Average member worth "+money(d.avg_week*52)+" a year."],["fp","Fitness Passport members","x",500,2600,10,function(v){return v.toLocaleString("en-NZ")},"From M2 Core today."],["fpv","Extra Passport visits per member, a month","a",0,4,0.25,function(v){return v.toFixed(2)},"At "+money(d.fp_rate)+" a visit, the current top rate."],["churn","Monthly churn cut (percentage points)","a",0,1,0.05,function(v){return v.toFixed(2)+" pts"},"Earlier calls to red members is how this moves."],["upg","Daily to Perform upgrades a month","a",0,20,1,function(v){return v},"$20 a week more each."],["hours","Admin hours saved a week","a",0,30,1,function(v){return v+" h"},"Exports, spreadsheets, manual texts, chasing debt. At $30 an hour."],["dev","Developer and hosting a month","a",0,6000,250,function(v){return money(v)},"Milos, hosting, fixes, security. A real cost of owning it."]];
 $("#whyS").innerHTML=S.map(function(x){return '<div class="sld"><label for="r_'+x[0]+'">'+esc(x[1])+'<span class="src '+x[2]+'">'+(x[2]==="x"?"Real":"Assumption")+'</span></label><output id="o_'+x[0]+'">'+x[6](ROI[x[0]])+'</output><input type="range" id="r_'+x[0]+'" data-k="'+x[0]+'" min="'+x[3]+'" max="'+x[4]+'" step="'+x[5]+'" value="'+ROI[x[0]]+'"><span class="h">'+esc(x[7])+'</span></div>'}).join("");
 S.forEach(function(x){$("#r_"+x[0]).oninput=function(){ROI[x[0]]=+this.value;$("#o_"+x[0]).textContent=x[6](ROI[x[0]]);whyLedger()}});
 whyLedger();
})}
function whyLedger(){var d=ROI.d,avg=d.avg_week*52;
 var L=[["Passport visits",ROI.fp*ROI.fpv*12*d.fp_rate],["Members kept by lower churn",ROI.paying*(ROI.churn/100)*12*avg*0.5],["Daily to Perform upgrades",ROI.upg*12*20*52*0.5],["Admin time back",ROI.hours*30*52],["GymMaster down to doors only (half a year)",Math.max(0,d.gm_cost-(d.gm_doors||350))*6]];
 var C=[["Developer and hosting",ROI.dev*12],["Ezidebit fees, if M2 pays them",(d.debits_month||0)*d.debit_fee*12]];
 var up=L.reduce(function(a,x){return a+x[1]},0),cost=C.reduce(function(a,x){return a+x[1]},0),net=up-cost;
 $("#whyL").innerHTML=L.map(function(x){return '<div class="ln"><span>'+esc(x[0])+'</span><b>+'+money(x[1])+'</b></div>'}).join("")+C.map(function(x){return '<div class="ln c"><span>'+esc(x[0])+'</span><b>-'+money(x[1])+'</b></div>'}).join("")+'<div style="display:flex;justify-content:space-between;align-items:flex-end;gap:12px;padding-top:16px;flex-wrap:wrap"><div><div style="color:#9A9A92;font-size:12px;font-weight:600;letter-spacing:.08em;text-transform:uppercase">Net upside, year one</div><b style="font:900 44px/1 Archivo,Arial,sans-serif;color:'+(net>=0?"var(--lime)":"#FF8A7A")+'">'+money(net)+'</b></div><div style="text-align:right"><div style="color:#9A9A92;font-size:12px;font-weight:600;letter-spacing:.08em;text-transform:uppercase">Return on cost</div><b style="font:900 28px/1 Archivo,Arial,sans-serif;color:#fff">'+(cost?(up/cost).toFixed(1)+"x":"-")+'</b></div></div>';
 $("#whyUp").textContent=kfmt(net);
}
