#!/usr/bin/env python3
"""Turn schema.sql and seed_staff.sql into src/schema_sql.js, so the worker can set up
its own database on first run (no wrangler commands needed). Run after editing schema.sql."""
import json, os, re, sqlite3
here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def statements(path):
    out, buf = [], ""
    for line in open(os.path.join(here, path)):
        line = re.sub(r"\s--\s.*$", "", line.rstrip("\n")) if not line.lstrip().startswith("--") else ""
        if not line.strip():
            continue
        buf += line + "\n"
        if sqlite3.complete_statement(buf):
            out.append(buf.strip())
            buf = ""
    assert not buf.strip(), "unfinished statement in " + path
    return out

schema, staff = statements("schema.sql"), statements("seed_staff.sql")
db = sqlite3.connect(":memory:")
for s in schema + staff:
    db.execute(s)
js = ("// Generated by scripts/gen_schema.py from schema.sql and seed_staff.sql. Do not edit by hand.\n"
      "export const SCHEMA = " + json.dumps(schema, indent=0) + ";\n"
      "export const STAFF_SEED = " + json.dumps(staff, indent=0) + ";\n")
open(os.path.join(here, "src/schema_sql.js"), "w").write(js)
print(len(schema), "schema statements,", len(staff), "staff statements")
